services:
  test:
    build:
      context: .
      dockerfile: ./apps/test/Dockerfile
      target: development
    command: pnpm run start:dev test
    env_file:
      - ./apps/test/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env