services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env